# Author/creator: nattapat2871 (https://nattapat2871.me)

org.gradle.jvmargs=-Xmx1G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.19

mod_version=1.2.4-beta3+26.2
maven_group=com.namlauncher
archives_base_name=namlauncher-branding-bridge
